/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.TestPaymentServiceProvider;
	import flexUnitTests.TestSecurityKeyValidatorVersion1;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_TestSecurityKeyValidatorVersion1_obj:flexUnitTests.TestSecurityKeyValidatorVersion1;
		
		private var flexUnitTests_TestPSP_obj:flexUnitTests.TestPaymentServiceProvider;
	}
}